/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function closeWindow(id: number): void;

export declare function createWindow(
    url: string,
    title: string,
    initScript: string | undefined | null,
    options: WindowOptions,
    onEvent: (event: WindowEvent) => void,
): number;

export declare function quit(): void;

export declare function setAppUserModelId(id: string): void;

export declare function showWindow(id: number): void;

export interface WindowEvent {
    id: number;
    kind: WindowEventKind;
    message?: string;
}

export declare enum WindowEventKind {
    Created = 0,
    Closed = 1,
    Error = 2,
}

export interface WindowOptions {
    visible: boolean;
    decorations: boolean;
    center: boolean;
    width?: number;
    height?: number;
    backgroundColor?: Array<number>;
}
